### ISSUE TITLE
Support For Immutable Objects

### ISSUE THREAD

**Issue by monksy** [jacek99/javabuilders#2]
I've noticed that PropertyUtils only looks for properties that contain only a set Method. However, are there any plans in the future to support an immutable object? (Read-only)

**Comment by jacek99** [comment]
Sorry for not replying earlier, I had my notifications off on this old project.

I will try to look at that in the next few weeks...

**Comment by jacek99** [comment]
the JavaFX builder will support both unidrectional and bidirectional binding using the regular JavaFX APIs

**Comment by jacek99** [comment]
Closed as the binding support via "bind" (unidrectional) and "bindBidirectional" (bidirectional) is already in the FX JavaBuilder on the 2.0.0 branch

**Comment by monksy** [comment]
What is the FX JavaBuilder branch? Is this a new release of JavaBuilders?

**Comment by jacek99** [comment]
It is in on the 2.0.0 branch that I am working.

A JavaFX version will come out once I am done with it, probably in a few weeks, maybe months, time permitting.

**Comment by jacek99** [comment]
See:
https://github.com/jacek99/javabuilders/tree/2.0.0/javafx/javafx-sample-person-app

as an example
